#%RAML 1.0 Trait
responses:
  201:
    description: "Resource created on server. e.g. examples/Customer.json, examples/Order.json"
    body:
      application/json:
        type: <<typeName>>
      
